name: CI

on: [push, pull_request]

jobs:
  build-binary:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build binary
      run: |
        docker run --rm -v ${PWD}:/project garyodernichts/moonlightbuilder make dist
    - uses: actions/upload-artifact@v2
      with:
       name: moonlight-wiiu
       path: dist/*
