name: CI

on: [push, pull_request]

jobs:
  build-binary:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build binary
      run: |
        docker run --rm -v ${PWD}:/project garyodernichts/moonlightbuilder make
    - uses: actions/upload-artifact@master
      with:
       name: binary
       path: "*.rpx"
